// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SidebarNavIssueDemo
{
	public partial class MenuViewController : UIViewController
	{
		public MenuViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
