// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace SidebarNavIssueDemo
{
	public partial class stanfordNavBar : UINavigationBar
	{
		public stanfordNavBar (IntPtr handle) : base (handle)
		{
		}
	}
}
